globalconfig:
    tapirconfigversion: 17
    rpz:
        envelopesize:   400
    bootstrap:
        servers:        [ ]
        baseurl:        https://%s/api/v1/
        apitoken:       be-lean-and-mean-and-in-between
    observationtopics:
        - topic:        observations/down/tapir-pop
          pubkeyname:   tapir-analyze-pubkey
        - topic:        observations/down/tapir-pop/debug
          pubkeyname:   tapir-mgmt-debug-pubkey
    statustopics:
        - topic:        status/up/axfr/tapir-pop
          privkeyname:  edge-{EdgeId}-signer-pubkey
