globalconfig:
   tapirconfigversion:	17
   rpz:
      envelopesize:	400
   bootstrap:
      servers:		[ 77.72.231.135:5454, 1.2.3.4:1234 ]
      baseurl:		https://%s/api/v1/
      apikey:		be-lean-and-mean-and-in-between
