/*
 * Copyright (c) 2026 Johan Stenstam, johan.stenstam@internetstiftelsen.se
 */
package rig

import (
	"crypto/rand"
	"crypto/rsa"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/pem"
	"fmt"
	"math/big"
	"net"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// Generating pop's four configuration files.
//
// Written from what the code actually reads, not from the documentation --
// docs/configuration.md omits several keys that stop pop starting. Anything
// here that looks superfluous is satisfying a validate:"required" tag: the
// bootstrap server is disabled but still needs a name, addresses and TLS
// addresses, and the *bool fields must be present in the YAML or a nil pointer
// fails validation.
//
// MQTT is set to mode: ignored, which is why none of this needs a broker,
// client certificates or a keystore. Before that mode existed pop could not be
// started by a test at all.

func writeConfigs(p *Pop, cfg PopConfig, apiPort, tlsPort, bootPort, bootTLSPort int) error {
	if err := os.WriteFile(filepath.Join(EtcDir, rigMarker),
		[]byte("Written by the pop test rig. Safe to delete.\n"), 0o644); err != nil {
		return fmt.Errorf("writing the rig marker: %w", err)
	}

	// pop refuses to start if it cannot build a TLS config for its API server
	// -- and apiserver.tlsaddresses cannot be left empty either, because it is
	// validate:"required". So the rig mints a throwaway CA and server
	// certificate rather than requiring the operator to supply real ones for a
	// listener no test uses. Same family as issue #191: a component that could
	// simply not be offered takes the whole daemon down instead.
	if err := mintCerts(p.WorkDir); err != nil {
		return fmt.Errorf("minting rig certificates: %w", err)
	}

	sources, err := renderSources(p, cfg.Sources)
	if err != nil {
		return err
	}

	files := map[string]string{
		"dnstapir-pop.yaml": renderMain(p, apiPort, tlsPort, bootPort, bootTLSPort),
		"pop-sources.yaml":  sources,
		"pop-outputs.yaml":  renderOutputs(cfg.Downstream),
		"pop-policy.yaml":   renderPolicy(p),
	}
	for name, body := range files {
		if err := os.WriteFile(filepath.Join(EtcDir, name), []byte(body), 0o644); err != nil {
			return fmt.Errorf("writing %s: %w", name, err)
		}
	}
	return nil
}

func renderMain(p *Pop, apiPort, tlsPort, bootPort, bootTLSPort int) string {
	return fmt.Sprintf(`# Generated by the pop test rig. Do not edit; regenerated on every run.
log:
   mode:        normal
   file:        %[1]s/pop.log
   verbose:     false
   debug:       false

services:
   rpz:
      zonename:    %[2]s
      serialcache: %[1]s/pop-serial.yaml
   reaper:
      interval:    3600
   refreshengine:
      active:      true

service:
   reset_soa_serial: false
   maxrefresh:       3600

apiserver:
   active:       true
   name:         rig-api
   key:          rig-api-key
   addresses:    [ 127.0.0.1:%[3]d ]
   tlsaddresses: [ 127.0.0.1:%[4]d ]

dnsengine:
   active:       true
   name:         rig-dns
   addresses:    [ %[5]s ]
   logfile:      %[1]s/pop-dnsengine.log
   verbose:      false
   debug:        false

bootstrapserver:
   active:       false
   name:         rig-bootstrap
   addresses:    [ 127.0.0.1:%[6]d ]
   tlsaddresses: [ 127.0.0.1:%[7]d ]
   logfile:      %[1]s/pop-bootstrap.log

tapir:
   # The whole reason this rig can run without a broker, a private CA or a
   # keystore. See issue #191.
   mqtt:
      mode:      ignored
      logfile:   %[1]s/pop-mqtt.log
   config:
      active:    false
   status:
      active:    false

# Throwaway, minted per run. pop needs these to bring up its HTTPS API
# listener, and will not start without them.
certs:
   certdir:      %[1]s/certs
   cacertfile:   %[1]s/certs/ca.crt
   tapir-pop:
      cert:      %[1]s/certs/server.crt
      key:       %[1]s/certs/server.key
`, p.WorkDir, p.ZoneName, apiPort, tlsPort, p.DNSAddr, bootPort, bootTLSPort)
}

func renderSources(p *Pop, sources []Source) (string, error) {
	var b strings.Builder
	b.WriteString("# Generated by the pop test rig.\nsources:\n")
	for _, s := range sources {
		if s.Type == "" {
			return "", fmt.Errorf("source %q has no list type", s.Name)
		}
		switch {
		case s.Feed != nil && s.Domains != nil:
			return "", fmt.Errorf("source %q is both a feed and a file; pick one", s.Name)

		case s.Feed != nil:
			fmt.Fprintf(&b, `   %[1]s:
      active:      true
      name:        %[1]s
      description: "rig xfr source"
      type:        %[2]s
      format:      rpz
      source:      xfr
      upstream:    %[3]s
      zone:        %[4]s
`, s.Name, s.Type, s.Feed.Addr(), s.Feed.Zone())

		default:
			// A file source, written into the working directory so nothing
			// outside it is touched.
			path := filepath.Join(p.WorkDir, s.Name+".domains")
			body := strings.Join(s.Domains, "\n")
			if body != "" {
				body += "\n"
			}
			if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
				return "", fmt.Errorf("writing source file for %s: %w", s.Name, err)
			}
			fmt.Fprintf(&b, `   %[1]s:
      active:      true
      name:        %[1]s
      description: "rig file source"
      type:        %[2]s
      format:      domains
      source:      file
      filename:    %[3]s
`, s.Name, s.Type, path)
		}
	}
	return b.String(), nil
}

func renderOutputs(downstream string) string {
	return fmt.Sprintf(`# Generated by the pop test rig.
outputs:
   rig-downstream:
      active:      true
      name:        rig-downstream
      description: "rig downstream"
      type:        doubtlist
      format:      rpz
      downstream:  %s
`, downstream)
}

// renderPolicy uses numsources: 1 so that a single doubtlist hit is enough to
// produce output. The graded thresholds are worth testing in their own right,
// but a rig that needs three sources to agree before anything appears makes
// every other test harder to write.
func renderPolicy(p *Pop) string {
	return fmt.Sprintf(`# Generated by the pop test rig.
policy:
   logfile: %s/pop-policy.log
   allowlist:
      action: allowlist
   denylist:
      action: nxdomain
   doubtlist:
      numsources:
         limit:  1
         action: nxdomain
      numtapirtags:
         limit:  2
         action: drop
      denytapir:
         tags:   [ likelymalware, badip ]
         action: drop
`, p.WorkDir)
}

// mintCerts writes a throwaway CA and a server certificate for 127.0.0.1 into
// dir/certs. They exist only to let pop's HTTPS listener start; nothing in the
// rig connects to it.
func mintCerts(dir string) error {
	cdir := filepath.Join(dir, "certs")
	if err := os.MkdirAll(cdir, 0o755); err != nil {
		return err
	}

	caKey, err := rsa.GenerateKey(rand.Reader, 2048)
	if err != nil {
		return err
	}
	caTmpl := &x509.Certificate{
		SerialNumber:          big.NewInt(1),
		Subject:               pkix.Name{CommonName: "pop-rig-ca"},
		NotBefore:             time.Now().Add(-time.Hour),
		NotAfter:              time.Now().Add(24 * time.Hour),
		IsCA:                  true,
		KeyUsage:              x509.KeyUsageCertSign | x509.KeyUsageDigitalSignature,
		BasicConstraintsValid: true,
	}
	caDER, err := x509.CreateCertificate(rand.Reader, caTmpl, caTmpl, &caKey.PublicKey, caKey)
	if err != nil {
		return err
	}
	caCert, err := x509.ParseCertificate(caDER)
	if err != nil {
		return err
	}

	srvKey, err := rsa.GenerateKey(rand.Reader, 2048)
	if err != nil {
		return err
	}
	srvTmpl := &x509.Certificate{
		SerialNumber: big.NewInt(2),
		Subject:      pkix.Name{CommonName: "pop-rig"},
		NotBefore:    time.Now().Add(-time.Hour),
		NotAfter:     time.Now().Add(24 * time.Hour),
		KeyUsage:     x509.KeyUsageDigitalSignature | x509.KeyUsageKeyEncipherment,
		ExtKeyUsage:  []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth},
		IPAddresses:  []net.IP{net.ParseIP("127.0.0.1")},
		DNSNames:     []string{"localhost"},
	}
	srvDER, err := x509.CreateCertificate(rand.Reader, srvTmpl, caCert, &srvKey.PublicKey, caKey)
	if err != nil {
		return err
	}

	write := func(name, typ string, der []byte) error {
		f, err := os.OpenFile(filepath.Join(cdir, name), os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0o600)
		if err != nil {
			return err
		}
		defer f.Close()
		return pem.Encode(f, &pem.Block{Type: typ, Bytes: der})
	}
	if err := write("ca.crt", "CERTIFICATE", caDER); err != nil {
		return err
	}
	if err := write("server.crt", "CERTIFICATE", srvDER); err != nil {
		return err
	}
	return write("server.key", "RSA PRIVATE KEY", x509.MarshalPKCS1PrivateKey(srvKey))
}
