name: CI
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test build before merge
        uses: actions/checkout@v2

      - name: Test build
        run: |
          make
